[features]
seeds = false
skip-lint = false

[programs.localnet]
risk_game = "3BxfMQouUVCckUpmbyfF9eGeHnzfJSJPzuZPpCvt99E7"
territory = "2cdfpKZqQxfHKwtZ8WckqdYCT2CHAUaLMkzv1E5CktyQ"
player = "H4kwyhKMgNKT7sKdk1FhwzYDrYP6Rwf6YijxpGq6tVoh"

[programs.devnet]
risk_game = "G4irLCSNHfxh2eCVpXowciffLtbnwGm1mGXU28afPsPJ"
territory = "qkw6L9CVQxDqvKUeuR7JgBmhGohvidimLQ3BQNkudM6"
player = "6ubHTD2eKvQ9yUJAnbQ6PFDpuEaRg754wq3hGtVbQov9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/sam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/game",
    "programs/territory",
    "programs/player",
]

[toolchain]
anchor_version = "0.29.0"

[test]
startup_wait = 10000 