[features]
seeds = false
skip-lint = false

[programs.localnet]
risk_game = "G4irLCSNHfxh2eCVpXowciffLtbnwGm1mGXU28afPsPJ"

[programs.devnet]
risk_game = "G4irLCSNHfxh2eCVpXowciffLtbnwGm1mGXU28afPsPJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sam/.config/solana/id.json"

[workspace]
members = ["."]
types = "target/types"

[toolchain]
anchor_version = "0.29.0"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000 