[features]
seeds = false
skip-lint = false

[programs.localnet]
risk_game = "7WWspBhgdSxJHdvuBXsBffFM4Ls6LwtXjYeZ4o6T7kry"
territory = "A3MkCuY8bq8MkoD62dBu9n6e54PLxuK8u6vpopExApMg"
player = "31axM9hfTEAvD9Kx8CUQCHXdETYBK8L3Pnzf7usQutbB"

[programs.devnet]
risk_game = "G4irLCSNHfxh2eCVpXowciffLtbnwGm1mGXU28afPsPJ"
territory = "qkw6L9CVQxDqvKUeuR7JgBmhGohvidimLQ3BQNkudM6"
player = "6ubHTD2eKvQ9yUJAnbQ6PFDpuEaRg754wq3hGtVbQov9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/game",
    "programs/territory",
    "programs/player",
]

[toolchain]
anchor_version = "0.29.0"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 