[features]
seeds = false
skip-lint = false

[programs.localnet]
risk_game = "7GTG5YucwCqnmcHoeTVs8vwt9MhXjQdCXs8yToHpHPHC"
territory = "6YK2ZBHN2tCqbhYFPat3iLqYqSySSiVkMRjSfPUHS9sm"
player = "Crw8PgBMPQ8xHmLnT7oMdp4ePpAcHHPyZeJXZQmAU6Lf"

[programs.devnet]
risk_game = "G4irLCSNHfxh2eCVpXowciffLtbnwGm1mGXU28afPsPJ"
territory = "qkw6L9CVQxDqvKUeuR7JgBmhGohvidimLQ3BQNkudM6"
player = "6ubHTD2eKvQ9yUJAnbQ6PFDpuEaRg754wq3hGtVbQov9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "local-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/game",
    "programs/territory",
    "programs/player",
]

[toolchain]
anchor_version = "0.29.0"

[test]
startup_wait = 10000 